- CHANGELOG.md
- webpack.config.cli.dev.js
When building and testing stripes-components directly the `node_modules/stripes-components` is not present which caused issues when looking for css variables via `generateStripesAlias`.
This PR introduces `locateCssVariables` to also look for `lib/variables.css` in the local folder. 
Thank you @zburke for finding and coming with a solution for this issue.
https://issues.folio.org/browse/STCOR-511
> STCOR-511: Add locateCssVariables to postcss-loader loader

- test/webpack/stripes-config-plugin.spec.js
- test/webpack/stripes-webpack-plugin.spec.js
- webpack/stripes-config-plugin.js
- webpack/stripes-error-logging-plugin.js
- webpack/stripes-webpack-plugin.js
Pass `errorLogging` values from a `stripes.config.js` file into the
dynamically generated config module.
This is cribbed from https://github.com/folio-org/stripes-core/pull/1004, which did two things: 
1. publishing of error events
2. a webpack config to accept error-logging values via `stripes.config.js`
Now that webpacky things have been externalized here from `stripes-core`, this PR implements Part 2. 
Refs [STRWEB-2](https://issues.folio.org/browse/STRWEB-2)
> STRWEB-2 provide errorLogging plugin

- CHANGELOG.md
This ports https://github.com/folio-org/stripes-core/pull/1006 from
`stripes-core` to `stripes-webpack`, which was cleaved from
`stripes-core` just before that PR merged.
Refs [STRWEB-1](https://issues.folio.org/browse/STRWEB-1), [STCOR-421](https://issues.folio.org/browse/STCOR-421)
> STRWEB-1 remove hard-source-webpack-plugin

- webpack/serve.js
I don't know why I have struggled SO HARD to port this simple PR from
`stripes-core`, [where it was flawless](https://github.com/folio-org/stripes-core/pull/1006), to `stripes-webpack`, where I have
tried (#5) and tried again (#9) to do the exact same thing but I keep
screwing it up. Maybe `stripes-webpack` is jealous of the nice song?
I want to build without warnings
I want to `yarn` with no old deps
I want to see naked, that terminal
That console, so true errors shine through
@skomorokh put this in here
So now what, so now what?
Wanting, needing, waiting
Will this decruftify my build? (my build)
Hoping, praying
Will this decruftify my build?
I run it local
Not like `--cache`
I don't want an ancient devdep
I don't want abandoned devdeps either
I just want to run `yarn` cleanly
exit zero, …
> really REALLY remove hard-source-webpack-plugin

- CHANGELOG.md
- package.json
- webpack/babel-loader-rule.js
Add support for a new JSX transform which will allow for writing functional components without importing react.
https://issues.folio.org/browse/STRWEB-5
More info:
https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html
> STRWEB-5: Add support for new jsx transform

- CHANGELOG.md
- package.json
- webpack/stripes-translations-plugin.js
If translations exist in a /compiled subdirectory, then they will be preferred as the translations to use in the final bundle. Mixed compiled and uncompiled is acceptable and verified to work correctly at run-time
> Added handling for pulling compiled AST translations into final bundle.

- CHANGELOG.md
- test/webpack/stripes-translations-plugin.spec.js
- webpack/stripes-translations-plugin.js
Previously, if the `translations/${module}/` directory contained
accidental non-file cruft (i.e., it contained a directory), the
translations plugin would attempt to read those entries as files.
Predictably, this would fail. Such entries are now ignored and logged.
Refs [STRWEB-7](https://issues.folio.org/browse/STRWEB-7)
Attn: @AndrewIsh
> STRWEB-7 ignore non-file entries in translations directory

- CHANGELOG.md
- package.json
Provide `react` and `react-dom`, peer-deps of `react-hot-loader` among
others, in order to be able to install with `npm` `^7` without requiring
`--legacy-peer-deps`. Without specifying this, the react-dom version
would float to `17.0.2`, which conflicts with other libraries that do
not yet support `react` `^17`.
Refs [STRWEB-11](https://issues.folio.org/browse/STRWEB-11)
> STRWEB-11 correctly specify peerDependencies

- CHANGELOG.md
- webpack/babel-loader-rule.js
Some babel plugins must be configured consistently if they are enabled.
If they aren't, babel warns you loudly and repeatedly when building a
platform independently, i.e. outside a workspace:
```
Though the "loose" option was set to "false" in your @babel/preset-env config, 
it will not be used for @babel/plugin-proposal-private-methods since the "loose" 
mode option was set to "true" for @babel/plugin-proposal-class-properties.
The "loose" option must be the same for @babel/plugin-proposal-class-properties,
@babel/plugin-proposal-private-methods and 
@babel/plugin-proposal-private-property-in-object (when they are enabled): 
you can silence this warning by explicitly adding
["@babel/plugin-proposal-private-methods", { "loose": true }]
to the "plugins" section of your Babel config.
``` …
> STRWEB-12 consistently configure babel plugins

- CHANGELOG.md
- webpack/babel-loader-rule.js
Introduces the STRIPES_TRANSPILE_TOKENS environment variable which
includes a space delimited list of strings (typically namespaces) to use
in addition to "@folio" to determine if something needs
Stripes-flavoured transpilation.
https://issues.folio.org/browse/STRWEB-13
> STRWEB-13 Allow non-@folio modules to be transpiled

- CHANGELOG.md
- package.json
Depend on `^5.0.6` to avoid the breaking changes that were accidentally
introduced in `5.0.5` and then reverted in `5.0.6`.
Refs [STRWEB-15](https://issues.folio.org/browse/STRWEB-15)
> STRWEB-15 avoid buggy optimize-css-assets-webpack-plugin 5.0.5

- CHANGELOG.md
- package.json
Avoid `postcss` `v8`, inadvertently introduced in a patch version (see
https://github.com/NMFR/optimize-css-assets-webpack-plugin/issues/167).
Refs [STRWEB-19](https://issues.folio.org/browse/STRWEB-19)
> STRWEB-19 avoid buggy optimize-css-assets-webpack-plugin

- CHANGELOG.md
- index.js
- package.json
- webpack/babel-loader-rule.js
- webpack/babel-options.js
Export the babel config options so they may consumed by other modules
that need access to the config either to correctly handle linting
(STRIPES-742) or Jest/RTL testing (STRIPES-757).
Refs [STRWEB-22](https://issues.folio.org/browse/STRWEB-22)
> STRWEB-22 export babel config options

- CHANGELOG.md
- webpack/babel-options.js
This PR turns on `babel-plugin-lodash`.
Here are some stats from `platform-complete` before and after the change.
Before:
After:
> STRWEB-20: Setup babel-plugin-lodash correctly

- CHANGELOG.md
- package.json
Allow react 16 and 17 as peer-dependencies in order to avoid build
warnings.
Refs [STRWEB-25](https://issues.folio.org/browse/STRWEB-25), [UXPROD-3264](https://issues.folio.org/browse/UXPROD-3264)
> STRWEB-25 permit react 17

- webpack.config.cli.dev.shared.styles.js
- webpack/serve.js
For 'development' environment, the webpack aliases can be missing if running within a workspace. This code adds those aliases to development mode.
other imports within modules (for non-shared styles,, component-specific styles) should try using `~` before the import, e.g.
```
composes: multiSelectOptionList from '@folio/stripes-components/lib/MultiSelection/MultiSelect.css';
```
should become 
```
composes: multiSelectOptionList from '~@folio/stripes-components/lib/MultiSelection/MultiSelect.css';
```
As per direction from our version of CSS-loader here: https://github.com/webpack-contrib/css-loader/tree/v4.3.0#import
> Supply webpack aliases to serve

- package.json
- webpack.config.cli.dev.js
[`webpack` `v5` removed many polyfills that were present in `v4`](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed). This PR restores one of them, resolving this error message:
```
message: "Module not found: Error: Can't resolve 'crypto' in '/Users/zburke/projects/folio-org/stripes-components/node_modules/axe-core'\n"
```
> STRWEB-4 Add crypto-browserify depenency to polyfill crypto in axe test runs

- CHANGELOG.md
- package.json
- webpack.config.cli.dev.js
Reduces a bit of the noise when spinning up test suites due to mocha's node-functional version being its primary export....
This creates an alias for the 'mocha' import to its browser version (polyfills some of the node `'process` API)
based on the final comment here: https://github.com/mochajs/mocha/issues/2448#issuecomment-928822632
This reduces the console noise in the testing terminal, removing one or more occurrences of:
```
{
moduleIdentifier: '/home/runner/work/stripes-components/stripes-components/node_modules/mocha/lib/mocha.js',
moduleName: './node_modules/mocha/lib/mocha.js',
loc: '342:19-40',
message: 'Critical dependency: the request of a dependency is an expression',
moduleId: './node_modules/mocha/lib/mocha.js',
moduleTrace: [ [Object], [Object], [Object], [Object] ], …
```
> Alias browser mocha

- webpack.config.cli.dev.js
The hard-coded reference to mocha's browser version leaves old versions of mocha hanging...
The approach: test the resolution of the browser version, if not present, just use a plain 'mocha' path.
> Make mocha alias more universal

- CHANGELOG.md
- webpack.config.cli.dev.js
Fixed source maps not generating.
The issue was caused by changes in two config properties: `devtool` and `cache`
Through trial and error I found that the only `devtool` value that generated correct source maps was `inline-source-map`.
Still, source maps weren't generating without `cache.name` property. It should have a default value that should work (https://webpack.js.org/configuration/cache/#cachename), but for some reason it doesn't. 
[STRWEB-34](https://issues.folio.org/browse/STRWEB-34)
> STRWEB-34 Fix source maps are not generated in dev build

- CHANGELOG.md
- package.json
`@cerner/duplicate-package-checker-webpack-plugin` `2.2.0` introduced
new node engine restrictions without incrementing their major version.
Whoops. I suspect they didn't realize that their previous `>=10 || <13`
configuration short-circuited to `>=10`. Sigh.
Details: https://github.com/cerner/terra-toolkit/issues/730
Refs [STRWEB-35](https://issues.folio.org/browse/STRWEB-35)
> STRWEB-35 avoid buggy third-party-dep

- webpack.config.cli.dev.js
- webpack/babel-options.js
- webpack/utils.js
Include HMR plugins only when in development env. This was missed in the original PR.
https://issues.folio.org/browse/STRWEB-27
> STRWEB-27: Include HMR plugins only when in development env

- package.json
12.1.5 throwing a great deal of deprecation warnings during builds. The maintainers are seeking feedback about their `importFrom` properties. I suppose that's one way to do it.
This quiets the warnings of 
```
{
moduleIdentifier: '/home/runner/work/stripes-components/stripes-components/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[7].use[1]!/home/runner/work/stripes-components/stripes-components/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[7].use[2]!/home/runner/work/stripes-components/stripes-components/lib/global.css',
moduleName: './node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[7].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[7].use[2]!./lib/global.css',
message: 'Module Warning (from ./node_modules/postcss-loader/dist/cjs.js):\n' + …
```
> STRWEB-43 Lock postcss-custom-properties to 12.1.4

- package.json
- webpack.config.base.js
- webpack.config.cli.dev.js
- webpack.config.cli.js
- webpack/stripes-module-parser.js
https://issues.folio.org/browse/STRWEB-30
This PR does two things:
1. Introduces lazy loading for ui modules which allows for shrinking the size of the main js bundle (about 5 times).
Each UI module will end up in its own chunk:
This is a breaking change as additional changes will be required in stripes-core in order to support lazy loading:
https://github.com/folio-org/stripes-core/pull/1147
2. Splits out stripes-config into a separate chunk via `dependOn` option.
Stripes config in Folio is currently assembled via webpack virtual module (https://github.com/sysgears/webpack-virtual-modules). This plugin is a clever way to generate virtual (in memory) files dynamically. What it means in practice is that it fools webpack to think that it deals with a real module/file (like any other real …
> STRWEB-30: Turn on lazy loading for ui modules

- CHANGELOG.md
- package.json
It looks like we missed an upgrade to `autoprefixer` `v10`when we did the
`webpack` `5` and `postcss` `8` work under STRWEB-4. `v9` contains a
direct dependency on `postcss` `7`; `v10` contains a peer dependency on
`v8`. We're on `v8` now, so we want everything to be compatible with
that.
Refs [STRWEB-46](https://issues.folio.org/browse/STRWEB-46), [STRWEB-4](https://issues.folio.org/browse/STRWEB-4), [STCOM-963](https://issues.folio.org/browse/STCOM-963)
> STRWEB-46 use compatible autoprefixer

- CHANGELOG.md
- package.json
- webpack/build.js
Older versions of `add-asset-html-webpack-plugin` rely on older versions
of `glob-parent` (< 5.1.2) that contain a redos vulnerability,
CVE-2020-28469.
Refs [STRWEB-28](https://issues.folio.org/browse/STRWEB-28)
> STRWEB-28 use current add-asset-html-webpack-plugin

- CHANGELOG.md
- test/webpack/babel-loader-rule.spec.js
- webpack/babel-loader-rule.js
This is really just a clean-up job; in fact
`@folio/react-githubish-mentions` was not even part of the initial
commit for `package.json`, indicating it must have been removed from
`stripes-core` before this repo was split off. Anyway: we had a
lingering test case that mentioned it, but it was not a great test to
begin with, amounting to, "make sure ${items} are present in ${list}",
which just meant we had `${items}` hard-coded in two places instead of
one.
Refs [STRWEB-41](https://issues.folio.org/browse/STRWEB-41)
> STRWEB-41 omit any mention of react-githubish-mentions

- package.json
most modules that used @bigtest/mirage migrated to miragejs earlier. In the case of stripes-webpack, I'm not sure why the dependency is present...
> remove @bigtest/mirage dep

- CHANGELOG.md
- webpack/stripes-module-parser.js
https://issues.folio.org/browse/STRWEB-52
All modules including handlers are currently lazy-loaded via `react.lazy`:
https://github.com/folio-org/stripes-webpack/pull/42/files#diff-e2d205c418f31e84d2da3758111d8d588cfac741d152c953fad9283a0f7099d1R116
Unfortunately, this doesn't work for handlers because handlers define static methods:
https://github.com/folio-org/ui-servicepoints/blob/7c55718c0c4143d6b77dc8707a0507589f50af00/src/index.js#L13
https://github.com/folio-org/ui-servicepoints/blob/7c55718c0c4143d6b77dc8707a0507589f50af00/src/index.js#L9
these methods are invoked outside of react render context:
https://github.com/folio-org/stripes-core/blob/be772d924fca97e2189e954a1c9075c629b6f645/src/components/MainNav/ProfileDropdown/ProfileDropdown.js#L93
and they are lost when a handler …
> STRWEB-52: Do not lazy load handler modules

- CHANGELOG.md
- webpack/stripes-module-parser.js
For some reason when plugins are lazy-loaded the position of the menu component is not correctly applied.
This is specifically visible when the plugin is embedded directly in the action menu: 
https://github.com/folio-org/ui-inventory/blob/69c97906f4a8054776a551812ead87d374434b5a/src/components/InstancesList/InstancesList.js#L538-L551
At this point, I'm not sure why this happens. It could be because some CSS calculations are performed during the first render and since the lazy-loaded components are not present the calculations are not correctly applied.
The way the `create-inventory-records` plugin is used is also questionable (it is embedded in the menu where the button which opens the plugin is also part of the plugin).
This PR turns off lazy loading for plugins for now so we can move …
> STRWEB-53: Do not lazy load plugins

- CHANGELOG.md
- webpack/stripes-module-parser.js
We ran into multiple issues related to lazy loading in various modules:
https://issues.folio.org/browse/STCOM-1008
https://issues.folio.org/browse/STCOR-626
https://issues.folio.org/browse/STRWEB-53
https://issues.folio.org/browse/STRWEB-52
And a couple more related to `history.push`
We think most of them are fixed now but it's a lot of changes and who knows what else is not working as expected.
We decided to turn the lazy loading off for now so we can move forward with the release.
The plan is to turn it back on after the release is done so there is more time to experiment with it.
Thank you @zburke  for your voice of reason on this.
> STRWEB-55: Turn off lazy loading

- webpack/tsconfig.json
- webpack/typescript-loader-rule.js
`ts-loader` will not, by default, compile TS found within `node_modules`.  However, when platforms are built, module code is within `node_modules`, therefore, `ts-loader` should be permitted to compile TS from within `node_modules/@folio/...`.
> STRWEB-57: Allow TS compilation within node_modules

- CHANGELOG.md
- webpack/tsconfig.json
Somehow, TS test files are leaking into the bundle and then causing
errors during the "build" phase when their (dev) dependencies aren't
satisfied. It isn't really clear why they're leaking in, but this PR
makes sure they stay out.
Refs [STRWEB-60](https://issues.folio.org/browse/STRWEB-60)
> STRWEB-60 exclude TS test files from the build

- webpack.config.base.js
- webpack.config.cli.dev.js
https://issues.folio.org/browse/STRIPES-820
Point to `stripes-ui` as an entry point instead of `stripes-core`.
This PR needs to be merged after:
https://github.com/folio-org/stripes-core/pull/1256
> STRIPES-820: Point to stripes-ui as an entry

- package.json
Platform complete is currently failing with:
https://jenkins-aws.indexdata.com/job/Automation/job/build-platform-complete-snapshot/13912/consoleText
This is due to the issue with `enhanced-resolve v5.11.0` (thank you @zburke for pointing to it):
https://github.com/webpack/enhanced-resolve/issues/362
This PR locks `enhanced-resolve` to `"~5.10.0"` it also upgrades `ts-loader` to make sure a single version of `enhanced-resolve` is used in the dependency tree.
Fixes [STRWEB-61](https://issues.folio.org/browse/STRWEB-61)
> STRWEB-61 Lock enhanced-resolve to ~5.10.0

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/STRWEB-62
This PR reverts the changes from https://github.com/folio-org/stripes-webpack/pull/81 since this was fixed directly in webpack: https://github.com/webpack/enhanced-resolve/pull/364
> STRWEB-62: Remove enhanced-resolve resolutions entry

- CHANGELOG.md
- package.json
Bump from v3 to v4 to avoid deprecated transitive dependencies.
Refs [STRWEB-72](https://issues.folio.org/browse/STRWEB-72)
> STRWEB-72 bump css-minimizer-webpack-plugin to v4

- CHANGELOG.md
- package.json
- webpack.config.base.js
- webpack/babel-options.js
This unmaintained plugin now spews thousands of lines of alerts during install due to one of the webpack functions it leverages being saddled with a deprecation warning. The fix is utterly trivial, but the maintainers have been silent for weeks, not providing any faith that this will ever be addressed.
It was nice to have a small lodash footprint in our bundle, but it felt like a microoptimization given our bundlesize, and something that was not worth the benefit given the poor DX.
This effectively undoes [STRWEB-20](https://issues.folio.org/browse/STRWEB-20)/PR #28
Refs [STRWEB-73](https://issues.folio.org/browse/STRWEB-73)
> STRWEB-73 remove babel-plugin-lodash

- webpack/module-paths.js
This is an additional fix related to transpilation work merged in: https://github.com/folio-org/stripes-webpack/pull/73
The PR adds a check for `@folio/stripes` package.json before loading it.
> STRWEB-69: Check if @folio/stripes path exists before loading it

- CHANGELOG.md
- package.json
- test/webpack/esbuild-loader-rule.spec.js
- webpack.config.cli.dev.js
- webpack.config.cli.prod.js
- webpack.config.cli.transpile.js
- webpack/esbuild-loader-rule.js
https://issues.folio.org/browse/STRWEB-76
This PR replaces babel-loader with [esbuild-lodaer](https://github.com/esbuild-kit/esbuild-loader).
The results are pretty good. The time to build a single module took half the time. It's also 5x faster to build the entire platform (snapshot):
| Babel Loader  | Esbuild Loader |
| ------------- | ------------- |
| Single module  |  Single module  |
| ![users-module-babel](https://user-images.githubusercontent.com/63545/227561603-38c021cf-91e1-497d-a34d-19afcb6fb23f.png)  | ![users-module-esbuild](https://user-images.githubusercontent.com/63545/227561700-e53adc8e-f2ea-4828-af73-b20e4db2f460.png)  |
| Platform (snapshot)  |  Platform (snapshot)  |
| ![platform-snapshot-babel](https://user-images.githubusercontent.com/63545/227561908-d9f5790d-8255-4dd4 …
> STRWEB-76: Replace babel loader with esbuild loader

- CHANGELOG.md
- webpack/babel-options.js
Do not strip `data-test-*` attributes from builds. The bloat they add is minimal (0.5%, 40k out of ~7MB in a gzipped bundle)  and the instrumentation they allow is so so so useful.
Discussed and agreed to at [Slack#stripes-architecture on 2023-03-23](https://folio-project.slack.com/archives/CAN13SWBF/p1679628985648489).
Refs [STRWEB-75](https://issues.folio.org/browse/STRWEB-75)
> STRWEB-75 do not strip data-test attributes

- CHANGELOG.md
- package.json
`7.2.0` is buggy; require `7.2.1`.
Refs [STRWEB-79](https://issues.folio.org/browse/STRWEB-79)
> STRWEB-79 avoid buggy postcss-loader 7.2.0

- CHANGELOG.md
- webpack.config.cli.transpile.js
Remove unused css-minimizer-webpack-plugin. The plugin was removed in https://github.com/folio-org/stripes-webpack/pull/101 but this import was missed which now causes issues during transpilation.
https://issues.folio.org/browse/STRWEB-82
> STRWEB-82: Remove css-minimizer-webpack-plugin

- CHANGELOG.md
- package.json
Add missing @babel/plugin-* dependencies that are listed in babel-options.js
These missing plugins are causing errors in `ui-inventory` tests
[STRWEB-86](https://issues.folio.org/browse/STRWEB-86)
> STRWEB-86 Add missing @babel/plugin-* dependencies that are listed in babel-options.js

- CHANGELOG.md
- package.json
Breaking postcss-calc change: dropped support for node <14
> Upgrade postcss-calc (pairs with STCOM #2063)

- CHANGELOG.md
- webpack.config.cli.shared.styles.js
Reverts #107
[STRWEB-85](https://issues.folio.org/browse/STRWEB-85) is the cause behind [ERM-2935](https://issues.folio.org/browse/ERM-2935). We may be able to omit the line in question altogether, but until we can figure out, definitively, if that's true, we just need to revert and get ui-agreements back in business.
> STRWEB-85 revert

- CHANGELOG.md
- package.json
`esbuild-loader` `v3.1.0` causes build failures in platform-complete across many modules with complaints like,
```
ERROR in ./node_modules/@folio/data-import/src/components/DataFetcher/DataFetcher.js
Module build failed (from ./node_modules/esbuild-loader/dist/index.cjs):
Error: Transform failed with 1 error:
/Users/zburke/temp/platform-complete/node_modules/@folio/data-import/src/components/DataFetcher/DataFetcher.js:59:0:
ERROR: Transforming JavaScript decorators to the configured target environment ("es2015") is not supported yet
at failureErrorWithLog (/Users/zburke/temp/platform-complete/node_modules/esbuild/lib/main.js:1649:15)
at /Users/zburke/temp/platform-complete/node_modules/esbuild/lib/main.js:847:29
at responseCallbacks.<computed> …
```
> STRWEB-94 lock esbuild-loader to ~3.0.0 (#116)

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
In CI, bump from NodeJS 16 to 18.
Refs [STRWEB-96](https://issues.folio.org/browse/STRWEB-96)
> STRWEB-96 use NodeJS v18 in CI builds

- webpack.config.base.js
- webpack.config.cli.dev.js
- webpack.config.cli.js
- webpack.config.service.worker.js
- webpack/build.js
- webpack/serve.js
Include `service-worker.js`, pulled from
`@folio/stripes-core/src/service-worker.js`, in the output bundle so it can be registered via [`navigator.serviceWorker.register(...)`](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#registering_your_worker).
Refs [STRWEB-99](https://issues.folio.org/browse/STRWEB-99) [FOLIO-3627](https://issues.folio.org/browse/FOLIO-3627)
> STRWEB-99 bundle stripes-core's service-worker.js

- CHANGELOG.md
- webpack.config.service.worker.js
- webpack/build.js
- webpack/serve.js
Use a virtual module to forward some stripes-config values to the
service worker when it is bundled. These values must be compiled in
because global variables in a service worker are volatile and are thus
reset to their default (null) values on each sleep/wake cycle. Thus, the
only way to make these values permanently available is to compile them
in.
h/t @mkuklis and @JohnC-80 who did the heavy lifting here, helping to think through potential solutions and figuring out how to actually implement them in our highly customized build.
Refs [STRWEB-102](https://issues.folio.org/browse/STRWEB-102), [STCOR-759](https://issues.folio.org/browse/STCOR-759)
> STRWEB-102 forward stripes-config values to service worker

- CHANGELOG.md
- webpack.config.cli.shared.styles.js
Don't manipulate `config.resolve.extensions` for the benefit of CSS because it appears we're not actually leveraging it anywhere. Additional spot-testing across a variety of applications doesn't show any of the odd problems we saw when we first tried to clean this up in [STRWEB-85](https://issues.folio.org/browse/STRWEB-85).
Refs [STRWEB-90](https://issues.folio.org/browse/STRWEB-90)
> STRWEB-90 omit css alias cruft

- CHANGELOG.md
- package.json
- postcss.config.js
https://issues.folio.org/browse/STRWEB-103
Corresponds with https://github.com/folio-org/stripes-components/pull/2176
The feature added by `postcss-relative-color-syntax` are available in Chrome and Edge - and hopefully soon-to-be-actualized in Firefox and Safari (TP).
With it we can do relative color adjustements like brightening, darkening, alpha adjustment, etc. We use this to replace the `blend()` functionality that we had in the non-spec plugin `postcss-color-function`.
Adds and employs the `@csstools/postcss-relative-color-syntax` plugin.
> STRWEB-103 Refactor away from PostCSS Color Function

- CHANGELOG.md
- package.json
`favicons` `v7.1.5` bumps `sharp` from `v0.32.6` to `v0.33.1` and ain't nothin' building anymore. Jenkins errors look like
```
/home/jenkins/workspace/Automation/build-platform-complete-snapshot/node_modules/favicons-webpack-plugin/src/index.js:656
throw new Error(
^
Error: Could not find the npm peerDependency "favicons".
Please run:
npm i favicons
- or -
yarn add favicons
Error: Could not load the "sharp" module using the linux-x64 runtime
Possible solutions:
- Ensure optional dependencies can be installed:
npm install --include=optional sharp
yarn add sharp --ignore-engines
- Ensure your package manager supports multi-platform installation:
See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
npm install --os=linux --cpu=x64 sharp
npm install …
```
> STRWEB-105 lock favicons to v7.1.4 to avoid build failures

- CHANGELOG.md
- package.json
As part of [Jira STRIPES-900](https://issues.folio.org/browse/STRIPES-900), all modules should use one `typescript` version, inherited from this package.  This TS version should be the latest version.
> [STRWEB-104] Use latest TypeScript version

- CHANGELOG.md
- package.json
- webpack.config.cli.prod.js
Deployed platforms are not displaying their proper favicons as required by branding configuration from `stripes-cli`. 
TLDR: Remove usage/plugin-wrapping of `speed-measurer-webpack-plugin`... our implementation caused plugins to be seen as different types. :(
Favicons are implemented in our build system via the `favicons-webpack-plugin`. This ever-so-helpful plugin goes the distance by not only generating favicons for us, it also does the dirty(hacky?) work of digging into the separate instance of `html-webpack-plugin` and injects the appropriate content into the template that you've supplied. In the case of favicons, they end up as a bunch of `link[rel="icon"]`s in the page's base mark-up. In order to affect the configuration/behavior of `html-webpack-plugin`, `favicons-webpack-plugin` …
> STRWEB-108 Favicons not injected into html template.

- CHANGELOG.md
- webpack.config.cli.prod.js
Add `@folio/consortia-settings` to a platform build generates tens of thousands of lines of warnings form mini-css-extract-plugin about its inability to determine what order to assemble its CSS rules in because different files have the imports in a different order.
It seems likely we don't have to worry about this since per-module CSS will be scoped to that module by postcss, and shared CSS will just be in stripes-components, but this could be riskier than I realize, and a better approach may be to try to figure out what is happening in `@folio/consortia-settings` that is different than every other module we've added to the platform so far.
Refs [STRWEB-110](https://folio-org.atlassian.net/browse/STRWEB-110)
> STRWEB-110 ignore order of CSS imports

- CHANGELOG.md
- webpack.config.base.js
Support `?raw` to load arbitrary text files as strings, permitting, for example, a large XSLT file to be easily imported.
Usage:
```
import txtFile from "./someTxtFile.txt?raw"
```
CC: @mnscholz
Refs [STRWEB-109](https://folio-org.atlassian.net/browse/STRWEB-109)
> STRWEB-109 allow loading of arbitrary text files

- .github/workflows/ui.yml
There is no module-descriptor here.
Refs [STRWEB-119](https://folio-org.atlassian.net/browse/STRWEB-119), [STRIPES-938](https://folio-org.atlassian.net/browse/STRIPES-938)
> STRWEB-119 GA: omit publishing MD

- CHANGELOG.md
- package.json
`babel-plugin-remove-jsx-attributes` should have been removed in [STRWEB-75](https://folio-org.atlassian.net/browse/STRWEB-75) (PR #94). Now we've discovered a licensing incompatibility, so it not only _can_ be removed but _must_ be.
Refs [STRWEB-120](https://folio-org.atlassian.net/browse/STRWEB-120)
> STRWEB-120 remove babel-plugin-remove-jsx-attributes

- .github/workflows/ui.yml
* Change from `v1.1` to `v1`, which is the equivalent of migrating from `1.1` to `^1.0.0` to auto-include updates
* Add an if-condition to avoid running duplicate actions (pr and push are logged as separate events :roll_eyes:
Refs [STRWEB-117](https://folio-org.atlassian.net/browse/STRWEB-117)
> STRWEB-117 use less strict shared-workflow dep

- CHANGELOG.md
- package.json
Bump the minimum NodeJS version to v20 for compliance with the TC's currently-supported-technologies list as well as compatibility with dependencies that state a similar requirement.
Refs [STRWEB-127](https://folio-org.atlassian.net/browse/STRWEB-127)
> STRWEB-127 bump NodeJS to v20

- CHANGELOG.md
- package.json
This reverts commit 095f8eff4b3a44ed202c64bf70a4d9b5eab5be84.
The Jenkins nodes where we build platform-complete don't yet have NodeJS v20 and we don't know when it will be available. In the interest of making other changes (which, AFAIK, do directly not rely on NodeJS v20) available ASAP, we are reverting this change until our build nodes can support it.
Refs [STRWEB-127](https://folio-org.atlassian.net/browse/STRWEB-127)
> Revert "STRWEB-127 bump NodeJS to v20 (#155)"
